name: Run tests

on:
    push:
      branches:
        - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build project with python unittest
        run: |
          python -m unittest

        
	# your task: figure out the remainings steps 
	# that match your selected language. 
	# Hint: follow slide 15 for inspiration
	# You should first find an action that sets up the environment
	# for your selected programming language. 
	# You should then set up the steps to run similar to how you run
	# them locally