name: Run tests on push 

on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main
    
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: Build project
        run: |
          python -m unittest


name: Run tests on PR

on:
    pull_request:
      branches:
        - main
    
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: Build project
        run: |
          python -m unittest

      - name: Python Style Checker
        uses: andymckay/pycodestyle-action@0.1.3
